runtime:
  all_reduce_alg: null
  batchnorm_spatial_persistent: false
  dataset_num_private_threads: null
  default_shard_dim: -1
  distribution_strategy: mirrored
  enable_xla: false
  gpu_thread_mode: null
  loss_scale: null
  mixed_precision_dtype: null
  num_cores_per_replica: 1
  num_gpus: 0
  num_packs: 1
  per_gpu_thread_count: 0
  run_eagerly: false
  task_index: -1
  tpu: null
  tpu_enable_xla_dynamic_padder: null
  use_tpu_mp_strategy: false
  worker_hosts: null
task:
  allow_image_summary: false
  differential_privacy_config: null
  eval_input_partition_dims: []
  evaluation:
    report_per_class_iou: true
    report_train_mean_iou: true
  export_config:
    rescale_output: false
  freeze_backbone: true
  init_checkpoint: ./model_ckpt/best_ckpt-63
  init_checkpoint_modules: [backbone, decoder]
  losses:
    class_weights: []
    gt_is_matting_map: false
    ignore_label: 255
    l2_weight_decay: 4.0e-05
    label_smoothing: 0.0
    loss_weight: 1.0
    mask_scoring_weight: 1.0
    top_k_percent_pixels: 1.0
    use_binary_cross_entropy: false
    use_groundtruth_dimension: true
  model:
    backbone:
      mobilenet:
        filter_size_scale: 1.0
        model_id: MobileNetV2
        output_intermediate_endpoints: false
        output_stride: 16
        stochastic_depth_drop_rate: 0.0
      type: mobilenet
    decoder:
      aspp:
        dilation_rates: []
        dropout_rate: 0.0
        level: 4
        num_filters: 256
        output_tensor: false
        pool_kernel_size: []
        spp_layer_version: v1
        use_depthwise_convolution: false
      type: aspp
    head:
      decoder_max_level: null
      decoder_min_level: null
      feature_fusion: null
      level: 4
      logit_activation: null
      low_level: 2
      low_level_num_filters: 48
      num_convs: 0
      num_filters: 256
      prediction_kernel_size: 1
      upsample_factor: 1
      use_depthwise_convolution: false
    input_size: [128, 128, 3]
    mask_scoring_head: null
    max_level: 6
    min_level: 3
    norm_activation:
      activation: relu
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: true
    num_classes: 2
  name: null
  train_data:
    additional_dense_features: []
    apply_tf_data_service_before_batching: false
    aug_policy: null
    aug_rand_hflip: true
    aug_scale_max: 1.0
    aug_scale_min: 1.0
    autotune_algorithm: null
    block_length: 1
    cache: false
    crop_size: []
    cycle_length: 10
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: true
    dtype: float32
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 384
    groundtruth_padded_size: []
    image_feature:
      feature_name: image/encoded
      mean: !!python/tuple
      - 123.675
      - 116.28
      - 103.53
      num_channels: 3
      stddev: !!python/tuple
      - 58.395
      - 57.120000000000005
      - 57.375
    input_path: /content/train.tfrecord
    is_training: true
    output_size: [128, 128]
    prefetch_buffer_size: null
    preserve_aspect_ratio: false
    resize_eval_groundtruth: true
    seed: 21
    sharding: true
    shuffle_buffer_size: 1000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: ''
    trainer_id: null
    weights: null
  train_input_partition_dims: []
  validation_data:
    additional_dense_features: []
    apply_tf_data_service_before_batching: false
    aug_policy: null
    aug_rand_hflip: true
    aug_scale_max: 1.0
    aug_scale_min: 1.0
    autotune_algorithm: null
    block_length: 1
    cache: false
    crop_size: []
    cycle_length: 10
    decoder:
      simple_decoder:
        attribute_names: []
        mask_binarize_threshold: null
        regenerate_source_id: false
      type: simple_decoder
    deterministic: null
    drop_remainder: false
    dtype: float32
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    file_type: tfrecord
    global_batch_size: 384
    groundtruth_padded_size: [128, 128]
    image_feature:
      feature_name: image/encoded
      mean: !!python/tuple
      - 123.675
      - 116.28
      - 103.53
      num_channels: 3
      stddev: !!python/tuple
      - 58.395
      - 57.120000000000005
      - 57.375
    input_path: /content/valid.tfrecord
    is_training: false
    output_size: [128, 128]
    prefetch_buffer_size: null
    preserve_aspect_ratio: false
    resize_eval_groundtruth: false
    seed: 21
    sharding: true
    shuffle_buffer_size: 1000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: ''
    tfds_skip_decoding_feature: ''
    tfds_split: ''
    trainer_id: null
    weights: null
trainer:
  allow_tpu_summary: false
  best_checkpoint_eval_metric: mean_iou
  best_checkpoint_export_subdir: best_ckpt
  best_checkpoint_metric_comp: higher
  checkpoint_interval: 100
  continuous_eval_timeout: 3600
  eval_tf_function: true
  eval_tf_while_loop: false
  loss_upper_bound: 1000000.0
  max_to_keep: 5
  optimizer_config:
    ema: null
    learning_rate:
      cosine:
        alpha: 0.0
        decay_steps: 20000
        initial_learning_rate: 0.1
        name: CosineDecay
        offset: 0
      type: cosine
    optimizer:
      sgd:
        clipnorm: null
        clipvalue: null
        decay: 0.0
        global_clipnorm: null
        momentum: 0.9
        name: SGD
        nesterov: false
      type: sgd
    warmup:
      linear:
        name: linear
        warmup_learning_rate: 0.05
        warmup_steps: 100
      type: linear
  preemption_on_demand_checkpoint: true
  recovery_begin_steps: 0
  recovery_max_trials: 0
  steps_per_loop: 100
  summary_interval: 100
  train_steps: 20000
  train_tf_function: true
  train_tf_while_loop: true
  validation_interval: 100
  validation_steps: 100
  validation_summary_subdir: validation
